import { SolverGrid } from "./grid-types";

export const testGrid1: SolverGrid = [
  [
    { value: 8, miniGrid: "A" },
    { value: 6, miniGrid: "A" },
    { value: null, miniGrid: "A" },
    { value: null, miniGrid: "B" },
    { value: null, miniGrid: "B" },
    { value: null, miniGrid: "B" },
    { value: 4, miniGrid: "C" },
    { value: null, miniGrid: "C" },
    { value: null, miniGrid: "C" },
  ],
  [
    { value: 3, miniGrid: "A" },
    { value: null, miniGrid: "A" },
    { value: null, miniGrid: "A" },
    { value: null, miniGrid: "B" },
    { value: 8, miniGrid: "B" },
    { value: null, miniGrid: "B" },
    { value: null, miniGrid: "C" },
    { value: 1, miniGrid: "C" },
    { value: null, miniGrid: "C" },
  ],
  [
    { value: null, miniGrid: "A" },
    { value: null, miniGrid: "A" },
    { value: null, miniGrid: "A" },
    { value: 6, miniGrid: "B" },
    { value: null, miniGrid: "B" },
    { value: 1, miniGrid: "B" },
    { value: null, miniGrid: "C" },
    { value: null, miniGrid: "C" },
    { value: null, miniGrid: "C" },
  ],
  [
    { value: null, miniGrid: "D" },
    { value: null, miniGrid: "D" },
    { value: 7, miniGrid: "D" },
    { value: null, miniGrid: "E" },
    { value: 2, miniGrid: "E" },
    { value: null, miniGrid: "E" },
    { value: 1, miniGrid: "F" },
    { value: null, miniGrid: "F" },
    { value: 5, miniGrid: "F" },
  ],
  [
    { value: null, miniGrid: "D" },
    { value: null, miniGrid: "D" },
    { value: 8, miniGrid: "D" },
    { value: null, miniGrid: "E" },
    { value: null, miniGrid: "E" },
    { value: null, miniGrid: "E" },
    { value: 7, miniGrid: "F" },
    { value: null, miniGrid: "F" },
    { value: 2, miniGrid: "F" },
  ],
  [
    { value: 2, miniGrid: "D" },
    { value: null, miniGrid: "D" },
    { value: null, miniGrid: "D" },
    { value: 5, miniGrid: "E" },
    { value: 6, miniGrid: "E" },
    { value: null, miniGrid: "E" },
    { value: null, miniGrid: "F" },
    { value: null, miniGrid: "F" },
    { value: 8, miniGrid: "F" },
  ],
  [
    { value: null, miniGrid: "G" },
    { value: 4, miniGrid: "G" },
    { value: 3, miniGrid: "G" },
    { value: null, miniGrid: "H" },
    { value: null, miniGrid: "H" },
    { value: null, miniGrid: "H" },
    { value: 9, miniGrid: "I" },
    { value: null, miniGrid: "I" },
    { value: null, miniGrid: "I" },
  ],
  [
    { value: 6, miniGrid: "G" },
    { value: null, miniGrid: "G" },
    { value: null, miniGrid: "G" },
    { value: null, miniGrid: "H" },
    { value: 5, miniGrid: "H" },
    { value: null, miniGrid: "H" },
    { value: null, miniGrid: "I" },
    { value: null, miniGrid: "I" },
    { value: 1, miniGrid: "I" },
  ],
  [
    { value: null, miniGrid: "G" },
    { value: null, miniGrid: "G" },
    { value: null, miniGrid: "G" },
    { value: null, miniGrid: "H" },
    { value: null, miniGrid: "H" },
    { value: null, miniGrid: "H" },
    { value: 3, miniGrid: "I" },
    { value: null, miniGrid: "I" },
    { value: null, miniGrid: "I" },
  ],
];

export const testGrid2: SolverGrid = [
  [
    { value: null, miniGrid: "A" },
    { value: 9, miniGrid: "A" },
    { value: 3, miniGrid: "A" },
    { value: 1, miniGrid: "B" },
    { value: null, miniGrid: "B" },
    { value: 5, miniGrid: "B" },
    { value: 6, miniGrid: "C" },
    { value: 4, miniGrid: "C" },
    { value: null, miniGrid: "C" },
  ],
  [
    { value: 7, miniGrid: "A" },
    { value: null, miniGrid: "A" },
    { value: null, miniGrid: "A" },
    { value: null, miniGrid: "B" },
    { value: null, miniGrid: "B" },
    { value: null, miniGrid: "B" },
    { value: null, miniGrid: "C" },
    { value: null, miniGrid: "C" },
    { value: 5, miniGrid: "C" },
  ],
  [
    { value: 5, miniGrid: "A" },
    { value: null, miniGrid: "A" },
    { value: 1, miniGrid: "A" },
    { value: 2, miniGrid: "B" },
    { value: null, miniGrid: "B" },
    { value: 9, miniGrid: "B" },
    { value: 3, miniGrid: "C" },
    { value: null, miniGrid: "C" },
    { value: 7, miniGrid: "C" },
  ],
  [
    { value: 2, miniGrid: "D" },
    { value: null, miniGrid: "D" },
    { value: null, miniGrid: "D" },
    { value: null, miniGrid: "E" },
    { value: null, miniGrid: "E" },
    { value: null, miniGrid: "E" },
    { value: null, miniGrid: "F" },
    { value: null, miniGrid: "F" },
    { value: 3, miniGrid: "F" },
  ],
  [
    { value: null, miniGrid: "D" },
    { value: 3, miniGrid: "D" },
    { value: 6, miniGrid: "D" },
    { value: 9, miniGrid: "E" },
    { value: null, miniGrid: "E" },
    { value: 7, miniGrid: "E" },
    { value: 5, miniGrid: "F" },
    { value: 2, miniGrid: "F" },
    { value: null, miniGrid: "F" },
  ],
  [
    { value: 9, miniGrid: "D" },
    { value: null, miniGrid: "D" },
    { value: null, miniGrid: "D" },
    { value: null, miniGrid: "E" },
    { value: null, miniGrid: "E" },
    { value: null, miniGrid: "E" },
    { value: null, miniGrid: "F" },
    { value: null, miniGrid: "F" },
    { value: 1, miniGrid: "F" },
  ],
  [
    { value: 3, miniGrid: "G" },
    { value: null, miniGrid: "G" },
    { value: 2, miniGrid: "G" },
    { value: 4, miniGrid: "H" },
    { value: null, miniGrid: "H" },
    { value: 8, miniGrid: "H" },
    { value: 1, miniGrid: "I" },
    { value: null, miniGrid: "I" },
    { value: 9, miniGrid: "I" },
  ],
  [
    { value: 6, miniGrid: "G" },
    { value: null, miniGrid: "G" },
    { value: null, miniGrid: "G" },
    { value: null, miniGrid: "H" },
    { value: null, miniGrid: "H" },
    { value: null, miniGrid: "H" },
    { value: null, miniGrid: "I" },
    { value: null, miniGrid: "I" },
    { value: 4, miniGrid: "I" },
  ],
  [
    { value: null, miniGrid: "G" },
    { value: 4, miniGrid: "G" },
    { value: 7, miniGrid: "G" },
    { value: 3, miniGrid: "H" },
    { value: null, miniGrid: "H" },
    { value: 2, miniGrid: "H" },
    { value: 8, miniGrid: "I" },
    { value: 5, miniGrid: "I" },
    { value: null, miniGrid: "I" },
  ],
];
