const testGrid1 = [
  [
    { value: null, miniGrid: "A" },
    { value: null, miniGrid: "A" },
    { value: null, miniGrid: "A" },
    { value: null, miniGrid: "B" },
    { value: null, miniGrid: "B" },
    { value: null, miniGrid: "B" },
    { value: null, miniGrid: "C" },
    { value: null, miniGrid: "C" },
    { value: null, miniGrid: "C" },
  ],
  [
    { value: null, miniGrid: "A" },
    { value: null, miniGrid: "A" },
    { value: null, miniGrid: "A" },
    { value: null, miniGrid: "B" },
    { value: null, miniGrid: "B" },
    { value: null, miniGrid: "B" },
    { value: null, miniGrid: "C" },
    { value: null, miniGrid: "C" },
    { value: null, miniGrid: "C" },
  ],
  [
    { value: null, miniGrid: "A" },
    { value: null, miniGrid: "A" },
    { value: null, miniGrid: "A" },
    { value: null, miniGrid: "B" },
    { value: null, miniGrid: "B" },
    { value: null, miniGrid: "B" },
    { value: null, miniGrid: "C" },
    { value: null, miniGrid: "C" },
    { value: null, miniGrid: "C" },
  ],
  [
    { value: null, miniGrid: "D" },
    { value: null, miniGrid: "D" },
    { value: null, miniGrid: "D" },
    { value: null, miniGrid: "E" },
    { value: null, miniGrid: "E" },
    { value: null, miniGrid: "E" },
    { value: null, miniGrid: "F" },
    { value: null, miniGrid: "F" },
    { value: null, miniGrid: "F" },
  ],
  [
    { value: null, miniGrid: "D" },
    { value: null, miniGrid: "D" },
    { value: null, miniGrid: "D" },
    { value: null, miniGrid: "E" },
    { value: null, miniGrid: "E" },
    { value: null, miniGrid: "E" },
    { value: null, miniGrid: "F" },
    { value: null, miniGrid: "F" },
    { value: null, miniGrid: "F" },
  ],
  [
    { value: null, miniGrid: "D" },
    { value: null, miniGrid: "D" },
    { value: null, miniGrid: "D" },
    { value: null, miniGrid: "E" },
    { value: null, miniGrid: "E" },
    { value: null, miniGrid: "E" },
    { value: null, miniGrid: "F" },
    { value: null, miniGrid: "F" },
    { value: null, miniGrid: "F" },
  ],
  [
    { value: null, miniGrid: "G" },
    { value: null, miniGrid: "G" },
    { value: null, miniGrid: "G" },
    { value: null, miniGrid: "H" },
    { value: null, miniGrid: "H" },
    { value: null, miniGrid: "H" },
    { value: null, miniGrid: "I" },
    { value: null, miniGrid: "I" },
    { value: null, miniGrid: "I" },
  ],
  [
    { value: null, miniGrid: "G" },
    { value: null, miniGrid: "G" },
    { value: null, miniGrid: "G" },
    { value: null, miniGrid: "H" },
    { value: null, miniGrid: "H" },
    { value: null, miniGrid: "H" },
    { value: null, miniGrid: "I" },
    { value: null, miniGrid: "I" },
    { value: null, miniGrid: "I" },
  ],
  [
    { value: null, miniGrid: "G" },
    { value: null, miniGrid: "G" },
    { value: null, miniGrid: "G" },
    { value: null, miniGrid: "H" },
    { value: null, miniGrid: "H" },
    { value: null, miniGrid: "H" },
    { value: null, miniGrid: "I" },
    { value: null, miniGrid: "I" },
    { value: null, miniGrid: "I" },
  ],
];
